name:                 glados
version:              0.1.0.0
visibility:           public
id:                   glados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH
key:                  glados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH
license:              BSD-3-Clause
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/glados#readme
category:             Web
abi:                  ea39fb8898c2e1d25717c091d24ee293
exposed:              True
exposed-modules:
    AST.Ast AST.Semantics.Check AST.Semantics.CheckCall
    AST.Semantics.Type Common.Error Common.Type.Integer
    Common.Utils.Bytecode.File Common.Utils.Bytecode.Header
    Common.Utils.List Compiler.ASM.Assembler Compiler.ASM.AstToAsm
    Compiler.ASM.Builtins Compiler.ASM.Compiler
    Compiler.ASM.CompilerMonad Compiler.Bytecode.DisasmFinal
    Compiler.Bytecode.Encoder Compiler.Bytecode.Serializer
    Compiler.CompilerState Compiler.Instruction Compiler.PsInstruction
    Compiler.ResolveLabels.ResolveLabels
    Compiler.ResolveLabels.ResolveLabelsHelpers
    Compiler.ResolveLabels.Step2CallLabel
    Compiler.ResolveLabels.Step2GetFuncAddrLabel
    Compiler.ResolveLabels.Step2JumpIfFalseLabel
    Compiler.ResolveLabels.Step2JumpIfTrueLabel
    Compiler.ResolveLabels.Step2JumpLabel
    Compiler.ResolveLabels.Step2LabelDef
    Compiler.ResolveLabels.Step2MakeClosureLabel
    Compiler.ResolveLabels.Step2Real
    Compiler.ResolveLabels.Step2TailCallLabel Parser.Conditions
    Parser.Expression Parser.ImportSystem Parser.Lexer Parser.Statement
    VM.Bytecode.Reader VM.Bytecode.Runner VM.CallSnapshot
    VM.Instruction.Arithmetic VM.Instruction.Function
    VM.Instruction.Index VM.Instruction.Io VM.Instruction.List
    VM.Instruction.Logic VM.Instruction.Stack VM.Instruction.Struct
    VM.Instruction.System VM.Instruction.Variable VM.VMStack VM.VMState
    VM.VMValue

import-dirs:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/lib/x86_64-linux-ghc-9.10.3-5156/glados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH

library-dirs:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/lib/x86_64-linux-ghc-9.10.3-5156/glados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH

library-dirs-static:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/lib/x86_64-linux-ghc-9.10.3-5156/glados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH

dynamic-library-dirs:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/lib/x86_64-linux-ghc-9.10.3-5156

data-dir:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/share/x86_64-linux-ghc-9.10.3-5156/glados-0.1.0.0

hs-libraries:         HSglados-0.1.0.0-LZXErwlJYOhEDDVKfY8iVH
depends:
    base-4.20.2.0-65e9 binary-0.8.9.3-a089 bytestring-0.12.2.0-c0dd
    containers-0.7-95d4 megaparsec-9.7.0-9UbB08xev5pCZqUhG6iSR9
    mtl-2.3.1-0daa parser-combinators-1.3.0-6a9QYv7iPkbAlqewUrs2mh
    text-2.1.3-791b vector-0.13.2.0-10ul2xqfidcCdnZZWB9AGE

haddock-interfaces:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/doc/glados-0.1.0.0/glados.haddock

haddock-html:
    /woodpecker/src/github.com/CorpsB/Glados/.stack-work/install/x86_64-linux/7da536dd1b9327dace3b2b3b96d15870fbbb66514931a7edf7d80c72d55b381b/9.10.3/doc/glados-0.1.0.0
