when:
  - event: push
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: create_tag
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GIT_AUTHOR_NAME: "Woodpecker CI"
      GIT_AUTHOR_EMAIL: "ci@glados"
      GIT_COMMITTER_NAME: "Woodpecker CI"
      GIT_COMMITTER_EMAIL: "ci@glados"
    commands:
      - git fetch --tags
      - TAG="v$(date -u +%Y%m%d-%H%M%S)"
      - git tag "$TAG" "${CI_COMMIT_SHA}"
      - git push "https://x-access-token:$${GITHUB_TOKEN}@github.com/${CI_REPO_OWNER}/${CI_REPO_NAME}.git" "$TAG"
