kind: pipeline
name: Build test

depends_on:
  - coding-style

steps:
  - name: Build (On push)
    when:
      event: push
      branch:
        exclude:
          - gh-pages
    image: haskell:9.10.3
    volumes:
      - /var/lib/woodpecker/stack:/root/.stack
    commands:
      - make
      - make clean
      - make fclean
      - make re

  - name: Build (On PR)
    when:
      event: push
      branch:
        exclude:
          - gh-pages
    image: haskell:9.10.3
    commands:
      - make
      - make clean
      - make fclean
      - make re
