kind: pipeline
name: Coding-style checker

depends_on:
  - mainProtection

when:
  - event: [push, pull_request]
  branch:
    exclude:
      - gh-pages
      - Feat/Documentation

steps:
  - name: coding-style checker
    image: ghcr.io/epitech/coding-style-checker:latest
    commands:
      - ./tools/coding-style.sh

