kind: pipeline
name: Coding-style checker

when:
  event:
    include:
      - push
      - pull_request

steps:
  - name: coding-style checker
    image: ghcr.io/epitech/coding-style-checker:latest
    commands:
      - check.sh $(pwd) $(pwd)
      - |
        if test -s coding-style-reports.log; then
          echo "Coding style errors detected:"
          cat coding-style-reports.log
          exit 1
        else
          echo "No coding-style error detected, good work."
          exit 0
        fi

