kind: pipeline
name: Push Unitary Tests (On push)

depends_on:
  - build

when:
  event: [push, pull_request]

steps:
  - name: Unit test (On push)
    when:
      event: push
    image: haskell:9.10.3
    volumes:
      - /var/lib/woodpecker/stack:/root/.stack
    commands:
      - make test
      - ./tools/coverage_test.sh

  - name: Unit test (On PR)
    when:
      event: pull_request
    image: haskell:9.10.3
    commands:
      - make test
      - ./tools/coverage_test.sh
