when:
  event: push
  branch: Feat/Documentation

depends_on:
  - coverage
  - functional_test

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: build_docs
    image: haskell:9.10.3
    volumes:
      - /var/lib/woodpecker/stack:/root/.stack
    commands:
      - set -eu
      - cabal update
      - make doc
      - rm -rf site
      - mkdir -p site
      - DOC_DIR="$(find dist-newstyle -type d -path "*/doc/html/glados" | head -n 1)"
      - test -n "$DOC_DIR"
      - cp -r "$DOC_DIR"/* site/
      - test -f site/index.html

  - name: deploy_gh_pages
    image: alpine/git
    environment:
      GIT_AUTHOR_NAME: "Woodpecker CI"
      GIT_AUTHOR_EMAIL: "ci@glados"
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - set -eu
      - rm -rf out
      - |
        if ! git clone --depth 1 --branch gh-pages \
            "https://x-access-token:$${GITHUB_TOKEN}@github.com/${CI_REPO_OWNER}/${CI_REPO_NAME}.git" out
        then
          git clone --depth 1 \
            "https://x-access-token:$${GITHUB_TOKEN}@github.com/${CI_REPO_OWNER}/${CI_REPO_NAME}.git" out
          cd out
          git checkout --orphan gh-pages
        fi
      - cd out
      - git config user.name "Woodpecker CI"
      - git config user.email "ci@glados"
      - rm -rf ./*
      - cp -r ../site/* ./
      - rm -rf .woodpecker/auto_release.yml
      - rm -rf .woodpecker/build.yml
      - rm -rf .woodpecker/coding-style.yml
      - rm -rf .woodpecker/coverage.yml
      - rm -rf .woodpecker/dev-doc.yml
      - rm -rf .woodpecker/functional_test.yml
      - rm -rf .woodpecker/release.yml
      - touch .nojekyll
      - git add -A
      - git commit -m "publish ${CI_COMMIT_SHA}" || exit 0
      - git push origin gh-pages
