kind: pipeline
name: Functional tests

depends_on:
  - build

when:
  event: [push, pull_request]
  branch:
    exclude:
      - gh-pages

steps:
  - name: Basic tests
    when:
      event: push
      branch:
        exclude:
          - gh-pages
    image: haskell:9.10.3
    volumes:
      - /var/lib/woodpecker/stack:/root/.stack
    commands:
      - make
      - ./test/Functional/test.sh

  - name: Basic tests
    when:
      event: pull_request
      branch:
        exclude:
          - gh-pages
    image: haskell:9.10.3
    commands:
      - make
      - ./test/Functional/test.sh