kind: pipeline
name: Functional tests

when:
  event:
    include:
      - push
      - pull_request

steps:
  - name: Basic tests
    image: haskell:9.10.3
    commands:
      - make
      - ./tools/test/Functional/test.sh