kind: pipeline
name: Coding-style checker

when:
  event:
    include:
      - push
      - pull_request

steps:
  - name: check-preprod-branch
    image: alpine:latest
    when:
      event: pull_request
      branch: main
    commands:
      - echo "Event          : $CI_BUILD_EVENT"
      - echo "Source branch  : $CI_COMMIT_SOURCE_BRANCH"
      - echo "Target branch  : $CI_COMMIT_TARGET_BRANCH"
      - |
        if [ "$CI_COMMIT_SOURCE_BRANCH" = "preprod" ]; then
          echo "PR vers main depuis 'preprod'."
          exit 0
        else
          echo "Les PR vers 'main' doivent venir de 'preprod'."
          exit 1
        fi
