when:
  - event: tag

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  build_glados:
    image: haskell:9.10.3
    commands:
      - make clean
      - make

  create_release:
    image: woodpeckerci/plugin-github-release
    settings:
      api_key:
        from_secret: github_token
      owner: CorpsB
      repo: Glados
      tag: "${CI_COMMIT_TAG}"
      title: "Release ${CI_COMMIT_TAG}"
      files:
        - glados

      note: |        
        Commit:  ${CI_COMMIT_SHA}
        Author:  ${CI_COMMIT_AUTHOR}
